version: "3"
services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "80:3000"
    environment:
      - DB_HOST=#{DB_HOST}#
      - DB_NAME=#{DB_NAME}#
      - DB_USER=#{DB_USER}#
      - DB_PASS=#{DB_PASS}#
      - DB_PORT=5432
