version: 2
jobs:
  deploy_to_staging:
    docker:
      - image: google/cloud-sdk
    environment:
      PROJECT_NAME: "my-app"
      GOOGLE_PROJECT_ID: "xxxx"
      GOOGLE_COMPUTE_ZONE: "europe-west3-a"
      GOOGLE_CLUSTER_NAME: "cluster-1"
    steps:
      - checkout
      - run: 
          name: Deploy to Kubernetes
          command: |
            echo ${PROJECT_NAME}
            echo ${GOOGLE_PROJECT_ID}
            echo ${GOOGLE_COMPUTE_ZONE}
            echo ${GOOGLE_CLUSTER_NAME}
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - deploy_to_staging:
          filters:
            branches:
              only: master