---
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install dependencies
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - git
        - software-properties-common
        - gnupg2
        - python3
        - python3-pip
        - python3-setuptools
      state: latest
      update_cache: True

  - name: Install docker
    shell: curl https://get.docker.com | sh

  - name: Modify privilege
    become: true
    shell: usermod -aG docker $USER
    
  - name: python docker / docker-compse module
    become: true
    pip:
      name:
        - docker
        - docker-compose

  - name: Restart Docker Service
    service:
      name: docker
      state: restarted
