---
- hosts: pg-server
  vars_files:
    - vars_file.yml
  roles:
#    - install
#    - postgres
  become: true

- hosts: api-server
  vars_files:
    - vars_file.yml
  roles:
#    - install
    - api
  become: true
