---
  - name: Creates directory
    file:
      path: /home/{{ VM_USER_ADMIN }}/api
      state: directory
  
  - name: Clone Repo
    git:
      repo: https://github.com/alegorosito/tenpo.git
      dest: /home/{{ VM_USER_ADMIN }}/api/
      force: yes

  - replace:
      path: /home/{{ VM_USER_ADMIN }}/api/docker-compose.yml
      regexp: '#{DB_HOST}#'
      replace: '{{ DB_HOST }}'
  
  - replace:
      path: /home/{{ VM_USER_ADMIN }}/api/docker-compose.yml
      regexp: '#{DB_NAME}#'
      replace: '{{ DB_NAME }}'

  - replace:
      path: /home/{{ VM_USER_ADMIN }}/api/docker-compose.yml
      regexp: '#{DB_USER}#'
      replace: '{{ DB_USER }}'

  - replace:
      path: /home/{{ VM_USER_ADMIN }}/api/docker-compose.yml
      regexp: '#{DB_PASS}#'
      replace: '{{ DB_PASS }}'

  - name: Deploy API
    become: True
    shell:
      cmd: "docker-compose build && docker-compose up -d --force-recreate"
      chdir: /home/{{ VM_USER_ADMIN }}/api/
    register: outs

  - debug:
      var: outs.stdout_lines